id: P010741
initial_creation_type: ocr
source_metadata:
  id: bdr:W20193
  title: བཞད་སློང་བྱིས་པའི་འཛུམ་གྲོལ།
  author: ''
  volumes:
    f810295cdd2b412b8f128fbea5729182:
      image_group_id: I1KG23223
      title: ''
      volume_number: 1
      total_pages: 320
