id: P010741
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:22:24.341593
source_metadata:
  id: bdr:W20193
  title: བཞད་སློང་བྱིས་པའི་འཛུམ་གྲོལ།
  author: ''
  volumes:
    f810295cdd2b412b8f128fbea5729182:
      image_group_id: I1KG23223
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
